### ISSUE TITLE
chromedriver-helper を webdrivers に移行する

### ISSUE THREAD

**Issue by ethfumi** [ethfumi/ongeki-recorder#30]
+--------------------------------------------------------------------+
  |                                                                    |
  |  NOTICE: chromedriver-helper is deprecated after 2019-03-31.       |
  |                                                                    |
  |  Please update to use the 'webdrivers' gem instead.                |
  |  See https://github.com/flavorjones/chromedriver-helper/issues/83  |
  |                                                                    |
  +--------------------------------------------------------------------+

とのことらしいので移行したい。
単純に Gemfile の
gem 'chromedriver-helper'
を
gem 'webdrivers'
に置き換えるだけでは下記コマンドでスクリーンショットが取れなく、それだけでは移行できなさそうだった。
bundle exec ruby ongeki_web_driver.rb

**Comment by ethfumi** [comment]
chrome-driver のバージョンを上げただけでログイン時にエラーが出ていた。(webdriversの時と同じ)

差分
![image](https://user-images.githubusercontent.com/2544432/106912222-2b7e4800-6746-11eb-8c68-fa34faeaecb8.png)

```
[~/git/ongeki-recorder]: bundle exec ruby ongeki_web_driver.rb
Traceback (most recent call last):
	9: from ongeki_web_driver.rb:28:in `<main>'
	8: from ongeki_web_driver.rb:10:in `login'
	7: from /Users/fumi/git/ongeki-recorder/vendor/bundle/ruby/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver.rb:86:in `for'
	6: from /Users/fumi/git/ongeki-recorder/vendor/bundle/ruby/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/driver.rb:44:in `for'
	5: from /Users/fumi/git/ongeki-recorder/vendor/bundle/ruby/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/driver.rb:44:in `new'
	4: from /Users/fumi/git/ongeki-recorder/vendor/bundle/ruby/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/chrome/driver.rb:43:in `initialize'
	3: from /Users/fumi/git/ongeki-recorder/vendor/bundle/ruby/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/service.rb:69:in `start'
	2: from /Users/fumi/git/ongeki-recorder/vendor/bundle/ruby/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/socket_lock.rb:39:in `locked'
	1: from /Users/fumi/git/ongeki-recorder/vendor/bundle/ruby/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/service.rb:72:in `block in start'
/Users/fumi/git/ongeki-recorder/vendor/bundle/ruby/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/common/service.rb:142:in `connect_until_stable': unable to connect to chromedriver 127.0.0.1:9515 (Selenium::WebDriver::Error::WebDriverError)
```

**Comment by ethfumi** [comment]
unable to connect to chromedriver への対処方法。
けどこれをしたところで webdrivers に移行することはできなさそう。
https://qiita.com/kozy10/items/49fb49da1b12a410362a
